[package]
name = "wapuku-model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "wapuku_model"
path = "src/lib.rs"

[dependencies]
tobj = { version = "3.2"}

arrow = { version = "37.0.0", features = ["prettyprint"] }
arrow-schema = { version = "37.0.0", default-features = false }
parquet = { version = "37.0.0", default-features = false, features= ["arrow", "snap", "brotli", "flate2", "base64"] }
datafusion-common = { path = "../../arrow-datafusion/datafusion/common", version = "22.0.0", features = ["js"] }
datafusion-execution = { path = "../../arrow-datafusion/datafusion/execution", version = "22.0.0", features = ["js"] }
datafusion-expr = { path = "../../arrow-datafusion/datafusion/expr", version = "22.0.0" }
#datafusion-jit = { path = "../arrow-datafusion/datafusion/jit", version = "22.0.0" }
datafusion-optimizer = { path = "../../arrow-datafusion/datafusion/optimizer", version = "22.0.0" }
datafusion-physical-expr = { path = "../../arrow-datafusion/datafusion/physical-expr", version = "22.0.0" }
datafusion-row = { path = "../../arrow-datafusion/datafusion/row", version = "22.0.0" }
datafusion-sql = { path = "../../arrow-datafusion/datafusion/sql", version = "22.0.0" }
datafusion = { path = "../../arrow-datafusion/datafusion/core", version = "22.0.0", default-features = false, features = ["js"]   }
bytes = "1.4"
log = "0.4.17"

[dev-dependencies]
simplelog = "0.10.2"
ctor = "0.1.21"