[toolchain]
channel = "nightly"

[target.wasm32-unknown-unknown]
runner = 'cargo run -p wasm-bindgen-cli --bin wasm-bindgen-test-runner --'
rustflags = [
    # Enabled unstable APIs from web_sys
    "--cfg=web_sys_unstable_apis",
]

[unstable]
build-std = ["panic_abort", "std"]
[build]
target="wasm32-unknown-unknown"
