[target.wasm32-unknown-unknown]
runner = 'cargo run -p wasm-bindgen-cli --bin wasm-bindgen-test-runner --'
rustflags = [
    # Enabled unstable APIs from web_sys
    "--cfg=web_sys_unstable_apis",
    # Enables features which are required for shared-memory
    "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
    # Enables the possibility to import memory into wasm.
    # Without --shared-memory it is not possible to use shared WebAssembly.Memory.
    "-C", "link-args=--shared-memory --import-memory --max-memory=4294967296",
]

[unstable]
build-std = ["panic_abort", "std"]
[build]
target="wasm32-unknown-unknown"