name: build

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Ok"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: wapuku

      - name: Checkout my crossbeam
        uses: actions/checkout@v3
        with:
          repository: bushuyev/crossbeam
          path: polars
          ref: my_master

      - name: Checkout my rayon
        uses: actions/checkout@v3
        with:
          repository: bushuyev/rayon
          path: polars
          ref: master_my

      - name: Checkout my arrow2
        uses: actions/checkout@v3
        with:
          repository: bushuyev/arrow2
          path: polars
          ref: my_polars_2023-05-25

      - name: Checkout my polars
        uses: actions/checkout@v3
        with:
          repository: bushuyev/polars
          path: polars
          ref: my_main_2

      - name: Checkout wasm-bindgen
        uses: actions/checkout@v3
        with:
          repository: bushuyev/wasm-bindgen
          path: polars
          ref: main

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: build-wapuku
        run: |
          cd wapuku/wapuku-ui/www
          npm i
          npm run build:all
          cd dist && tar -zcvf ../../target/github-pages.tar.gz *

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'wapuku/wapuku-ui/target'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2