name: build

on:
  workflow_dispatch:

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Ok"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: wapuku

      - name: Checkout my polars
        uses: actions/checkout@v3
        with:
          repository: bushuyev/polars
          path: polars