name: build

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-all:
    runs-on: ubuntu-latest
    env:
      WAPUKU_RUST_TOOLCHAIN: nightly
    steps:
      - run: |
          echo "Ok"

      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: wapuku

      - name: Checkout my crossbeam
        uses: actions/checkout@v6
        with:
          repository: bushuyev/crossbeam
          path: crossbeam
          ref: my_master

      - name: Checkout my rayon
        uses: actions/checkout@v6
        with:
          repository: bushuyev/rayon
          path: rayon
          ref: my_master_polars_0_35_2

      - name: Checkout my polars
        uses: actions/checkout@v6
        with:
          repository: bushuyev/polars
          path: polars
          ref: my_main_0_35_2

      - name: Checkout wasm-bindgen
        uses: actions/checkout@v6
        with:
          repository: bushuyev/wasm-bindgen
          path: wasm-bindgen
          ref: my_main

#      - uses: actions-rust-lang/setup-rust-toolchain@v1
#        with:
#          toolchain: nightly

      - name: install rust
        run: |
          curl -y --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          rustup toolchain install "$WAPUKU_RUST_TOOLCHAIN" --profile minimal --component rust-src
          rustup target add wasm32-unknown-unknown --toolchain "$WAPUKU_RUST_TOOLCHAIN"

      - name: install wasm-pack
        run: |
          ls -R /home/runner/work/
          rustup toolchain list
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: build-wapuku
        run: |
          cd wapuku/wapuku-egui/www
          npm i
          cd ..
          ./build.sh

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './wapuku/wapuku-egui/www/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
